// src/components/AlertModal.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'

const props = withDefaults(
  defineProps<{
    isOpen: boolean
    title?: string
    message: string
    okText?: string
  }>(),
  {
    title: 'Внимание',
    okText: 'ОК',
  },
)

const emit = defineEmits<{
  close: []
}>()

const handleClose = () => {
  emit('close')
}

const handleEscape = (event: KeyboardEvent) => {
  if (event.key === 'Escape' && props.isOpen) {
    event.stopImmediatePropagation()
    handleClose()
  }
}

onMounted(() => {
  window.addEventListener('keydown', handleEscape)
})

onUnmounted(() => {
  window.removeEventListener('keydown', handleEscape)
})
</script>

<template>
  <Teleport to="body">
    <Transition
      enter-active-class="transition duration-200 ease-out"
      enter-from-class="opacity-0"
      enter-to-class="opacity-100"
      leave-active-class="transition duration-150 ease-in"
      leave-from-class="opacity-100"
      leave-to-class="opacity-0"
    >
      <div v-if="isOpen" class="fixed inset-0 z-[60]">
        <div class="fixed inset-0 bg-black/60 backdrop-blur-sm" @click="handleClose"></div>

        <div class="fixed inset-0 flex items-center justify-center p-4">
          <div
            class="relative bg-white dark:bg-slate-800 rounded-2xl shadow-2xl max-w-md w-full overflow-hidden border border-transparent dark:border-slate-700"
            @click.stop
          >
            <div class="p-6">
              <h3 class="text-xl font-bold text-gray-900 dark:text-slate-100 mb-2">{{ title }}</h3>
              <p class="text-gray-600 dark:text-slate-300">{{ message }}</p>
            </div>

            <div class="flex gap-3 p-6 pt-0">
              <button
                type="button"
                @click="handleClose"
                class="flex-1 px-4 py-2 bg-amber-500 text-white rounded-lg hover:bg-amber-600 transition-colors"
              >
                {{ okText }}
              </button>
            </div>

            <button
              type="button"
              @click="handleClose"
              class="absolute top-2 right-2 p-2 text-gray-400 hover:text-gray-600 dark:text-slate-400 dark:hover:text-slate-200 transition-colors"
            >
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

// frontend-react/src/components/AlertModal.tsx
import { useEffect } from 'react'

type AlertModalProps = {
  isOpen: boolean
  title?: string
  message: string
  okText?: string
  onClose: () => void
}

export function AlertModal({
  isOpen,
  title = 'Внимание',
  message,
  okText = 'ОК',
  onClose,
}: AlertModalProps) {
  useEffect(() => {
    if (!isOpen) return
    const onKey = (event: KeyboardEvent) => {
      if (event.key !== 'Escape') return
      event.preventDefault()
      event.stopImmediatePropagation()
      onClose()
    }
    window.addEventListener('keydown', onKey, true)
    return () => window.removeEventListener('keydown', onKey, true)
  }, [isOpen, onClose])

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-[60]">
      <div className="fixed inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />
      <div className="fixed inset-0 flex items-center justify-center p-4">
        <div
          className="relative w-full max-w-md overflow-hidden rounded-2xl border border-transparent bg-white shadow-2xl dark:border-slate-700 dark:bg-slate-800"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="p-6">
            <h3 className="mb-2 text-xl font-bold text-gray-900 dark:text-slate-300">{title}</h3>
            <p className="text-gray-600 dark:text-slate-400">{message}</p>
          </div>
          <div className="p-6 pt-0">
            <button
              type="button"
              onClick={onClose}
              className="w-full rounded-lg bg-amber-500 px-4 py-2 text-white transition-colors hover:bg-amber-600 dark:bg-amber-700 dark:text-amber-100 dark:hover:bg-amber-800"
            >
              {okText}
            </button>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="absolute top-2 right-2 p-2 text-gray-400 transition-colors hover:text-gray-600 dark:text-slate-500 dark:hover:text-slate-400"
            aria-label="Закрыть"
          >
            <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  )
}
