// src/components/DirectionModal.vue
<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted } from 'vue'
import { useScheduleStore } from '@/stores/schedule'
import AlertModal from '@/components/AlertModal.vue'
import ConfirmModal from '@/components/ConfirmModal.vue'
import type { Direction, NewDirection } from '@/types/lesson'

type DirectionDraft = NewDirection & { id: null }
type DirectionForm = Omit<Direction, 'id'> & { id: number | null }

const props = defineProps<{
  direction: Direction | DirectionDraft | null
  isOpen: boolean
}>()

const emit = defineEmits<{
  close: []
}>()

const store = useScheduleStore()

const isEditing = ref(false)
const editableDirection = ref<DirectionForm | null>(null)
const isConfirmOpen = ref(false)
const isAlertOpen = ref(false)
const alertMessage = ref('')
const directionToDelete = ref<number | null>(null)
const directionNameToDelete = ref('')

watch(
  () => props.direction,
  (direction) => {
    if (!direction) {
      editableDirection.value = null
      return
    }

    if (direction.id === null) {
      isEditing.value = true
      editableDirection.value = { id: null, name: '', description: null }
      return
    }

    isEditing.value = false
    editableDirection.value = JSON.parse(JSON.stringify(direction)) as DirectionForm
  },
  { immediate: true },
)

const showAlert = (message: string) => {
  alertMessage.value = message
  isAlertOpen.value = true
}

const enableEditing = () => {
  isEditing.value = true
}

const cancelEditing = () => {
  const current = props.direction
  if (!current) {
    emit('close')
    return
  }
  if (current.id === null) {
    emit('close')
    return
  }
  editableDirection.value = JSON.parse(JSON.stringify(current)) as DirectionForm
  isEditing.value = false
}

const requestDeleteDirection = () => {
  const current = props.direction
  if (!current || current.id === null) return
  directionToDelete.value = current.id
  directionNameToDelete.value = current.name
  isConfirmOpen.value = true
}

const handleDeleteConfirm = async () => {
  if (directionToDelete.value === null) return
  try {
    await store.deleteDirection(directionToDelete.value)
    directionToDelete.value = null
    directionNameToDelete.value = ''
    isConfirmOpen.value = false
    emit('close')
  } catch {
    showAlert('Не удалось удалить направление')
  }
}

const saveDirection = async () => {
  if (!editableDirection.value) return

  const normalizedName = editableDirection.value.name.trim()
  const currentDirectionId = editableDirection.value.id
  if (!normalizedName) {
    showAlert('Введите название направления')
    return
  }

  const isDuplicate = store.directions.some((direction) => {
    if (currentDirectionId !== null && direction.id === currentDirectionId) {
      return false
    }
    return direction.name.trim().toLowerCase() === normalizedName.toLowerCase()
  })
  if (isDuplicate) {
    showAlert('Такое направление уже существует')
    return
  }

  try {
    if (editableDirection.value.id !== null) {
      await store.updateDirection({
        id: editableDirection.value.id,
        name: normalizedName,
        description: editableDirection.value.description?.trim() || null,
      })
    } else {
      await store.addDirection({
        name: normalizedName,
        description: editableDirection.value.description?.trim() || null,
      })
    }

    emit('close')
  } catch (error) {
    const message = error instanceof Error ? error.message : ''
    showAlert(message ? `Не удалось сохранить направление: ${message}` : 'Не удалось сохранить направление')
  }
}

const handleEscape = (event: KeyboardEvent) => {
  if (event.key === 'Escape' && props.isOpen) {
    if (isConfirmOpen.value || isAlertOpen.value) return
    emit('close')
  }
}

onMounted(() => {
  window.addEventListener('keydown', handleEscape)
})

onUnmounted(() => {
  window.removeEventListener('keydown', handleEscape)
})
</script>

<template>
  <Teleport to="body">
    <Transition
      enter-active-class="transition duration-200 ease-out"
      enter-from-class="opacity-0"
      enter-to-class="opacity-100"
      leave-active-class="transition duration-150 ease-in"
      leave-from-class="opacity-100"
      leave-to-class="opacity-0"
    >
      <div v-if="isOpen" class="fixed inset-0 z-50">
        <div class="fixed inset-0 bg-black/60 backdrop-blur-sm" @click="emit('close')">
          <div class="fixed inset-0 flex items-center justify-center p-4">
            <div
              class="relative bg-white dark:bg-slate-800 rounded-2xl shadow-2xl max-w-lg w-full max-h-[90vh] overflow-hidden border border-transparent dark:border-slate-700"
              @click.stop
            >
              <div class="overflow-y-auto p-6" style="max-height: calc(90vh - 8px)">
                <template v-if="direction && !isEditing && direction.id !== null">
                  <h3 class="text-2xl font-bold text-gray-900 dark:text-slate-100 mb-4 pr-8">
                    {{ direction.name }}
                  </h3>
                  <div v-if="direction.description" class="mb-4">
                    <p class="text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wide mb-1">Описание</p>
                    <p class="text-sm text-gray-700 dark:text-slate-300 whitespace-pre-line">
                      {{ direction.description }}
                    </p>
                  </div>
                  <div class="mb-6 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 dark:border-amber-700/50 dark:bg-amber-900/20">
                    <p class="text-sm font-semibold text-amber-800">Внимание</p>
                    <p class="mt-1 text-sm text-amber-700">
                      При удалении направления все связанные занятия будут удалены из расписания без возможности
                      восстановления.
                    </p>
                  </div>
                  <div class="flex gap-2 mt-2 pt-4 border-t border-gray-200 dark:border-slate-700">
                    <button
                      type="button"
                      @click="enableEditing"
                      class="flex-1 px-4 py-2 bg-amber-500 text-white rounded-lg hover:bg-amber-600"
                    >
                      Редактировать
                    </button>
                    <button
                      type="button"
                      @click="requestDeleteDirection"
                      class="flex-1 px-4 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600"
                    >
                      Удалить
                    </button>
                  </div>
                </template>
                <template v-else-if="editableDirection">
                  <h3 class="text-xl font-bold text-gray-900 dark:text-slate-100 mb-4 pr-8">
                    {{ editableDirection.id === null ? 'Новое направление' : 'Редактирование' }}
                  </h3>
                  <form @submit.prevent="saveDirection" class="space-y-4">
                    <div>
                      <label for="direction-name" class="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-1">
                        Название направления
                      </label>
                      <input
                        id="direction-name"
                        v-model="editableDirection.name"
                        type="text"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg bg-white text-gray-900 focus:ring-2 focus:ring-amber-400 focus:border-transparent dark:bg-slate-900 dark:border-slate-600 dark:text-slate-100"
                        required
                      />
                    </div>
                    <div>
                      <label for="direction-description" class="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-1">
                        Описание направления
                      </label>
                      <textarea
                        id="direction-description"
                        v-model="editableDirection.description"
                        rows="4"
                        placeholder="Для кого это направление, что изучается на занятии и т.п."
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg bg-white text-gray-900 focus:ring-2 focus:ring-amber-400 focus:border-transparent dark:bg-slate-900 dark:border-slate-600 dark:text-slate-100"
                      />
                    </div>
                    <div class="flex gap-3 pt-4">
                      <button
                        type="submit"
                        class="flex-1 px-4 py-2 bg-amber-500 text-white rounded-lg hover:bg-amber-600 transition-colors"
                      >
                        Сохранить
                      </button>
                      <button
                        type="button"
                        @click="cancelEditing"
                        class="flex-1 px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-colors dark:bg-slate-700 dark:text-slate-200 dark:hover:bg-slate-600"
                      >
                        Отмена
                      </button>
                    </div>
                  </form>
                </template>
              </div>

              <button
                type="button"
                @click="emit('close')"
                class="absolute top-2 right-2 p-2 text-gray-400 hover:text-gray-600 dark:text-slate-400 dark:hover:text-slate-200 transition-colors cursor-pointer"
              >
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M6 18L18 6M6 6l12 12"
                  />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>

  <ConfirmModal
    :isOpen="isConfirmOpen"
    :message="`Вы уверены, что хотите удалить направление ${directionNameToDelete}? Связанные занятия будут удалены.`"
    @confirm="handleDeleteConfirm"
    @close="isConfirmOpen = false"
  />

  <AlertModal :isOpen="isAlertOpen" :message="alertMessage" @close="isAlertOpen = false" />
</template>

// frontend-react/src/components/DirectionModal.tsx
import { useEffect, useMemo, useState } from 'react'
import {
  createDirection,
  deleteDirection,
  updateDirection,
  type Direction,
  type NewDirection,
} from '../services/schedule'

type DirectionModalProps = {
  direction: Direction | null
  allDirections: Direction[]
  isOpen: boolean
  onClose: () => void
  onSaved: () => void
}

type DirectionDraft = {
  id: number | null
  name: string
  description: string | null
}

const cloneDirection = (direction: Direction): DirectionDraft => ({
  id: direction.id,
  name: direction.name,
  description: direction.description,
})

const buildEmptyDirection = (): DirectionDraft => ({
  id: null,
  name: '',
  description: null,
})

export function DirectionModal({ direction, allDirections, isOpen, onClose, onSaved }: DirectionModalProps) {
  const [isEditing, setIsEditing] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [draft, setDraft] = useState<DirectionDraft | null>(null)

  useEffect(() => {
    if (!isOpen) return
    if (direction) {
      setDraft(cloneDirection(direction))
      setIsEditing(false)
    } else {
      setDraft(buildEmptyDirection())
      setIsEditing(true)
    }
    setError(null)
  }, [direction, isOpen])

  useEffect(() => {
    const onEsc = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && isOpen) onClose()
    }
    window.addEventListener('keydown', onEsc)
    return () => window.removeEventListener('keydown', onEsc)
  }, [isOpen, onClose])

  const existingNames = useMemo(() => {
    if (!draft) return new Set<string>()
    return new Set(
      allDirections
        .filter((item) => item.id !== draft.id)
        .map((item) => item.name.trim().toLowerCase())
        .filter(Boolean),
    )
  }, [allDirections, draft])

  if (!isOpen || !draft) return null

  const handleSave = async () => {
    const normalizedName = draft.name.trim()
    if (!normalizedName) {
      setError('Введите название направления')
      return
    }
    if (existingNames.has(normalizedName.toLowerCase())) {
      setError('Такое направление уже существует')
      return
    }

    setError(null)
    setIsSubmitting(true)
    try {
      const payload: NewDirection = {
        name: normalizedName,
        description: draft.description?.trim() || null,
      }
      if (draft.id === null) {
        await createDirection(payload)
      } else {
        await updateDirection(draft.id, payload)
      }
      onSaved()
      onClose()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Не удалось сохранить направление')
    } finally {
      setIsSubmitting(false)
    }
  }

  const handleDelete = async () => {
    if (draft.id === null) return
    if (!window.confirm(`Вы уверены, что хотите удалить направление ${draft.name}? Связанные занятия будут удалены.`)) {
      return
    }

    setError(null)
    setIsSubmitting(true)
    try {
      await deleteDirection(draft.id)
      onSaved()
      onClose()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Не удалось удалить направление')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50">
      <div className="fixed inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose}>
        <div className="fixed inset-0 flex items-center justify-center p-4">
          <div
            className="relative max-h-[90vh] w-full max-w-lg overflow-hidden rounded-2xl border border-transparent bg-white shadow-2xl dark:border-slate-700 dark:bg-slate-800"
            onClick={(event) => event.stopPropagation()}
          >
            <div className="overflow-y-auto p-6" style={{ maxHeight: 'calc(90vh - 8px)' }}>
              {!isEditing && draft.id !== null ? (
                <>
                  <h3 className="mb-4 pr-8 text-2xl font-bold text-gray-900 dark:text-slate-100">{draft.name}</h3>
                  {draft.description && (
                    <div className="mb-4">
                      <p className="mb-1 text-xs font-semibold tracking-wide text-gray-500 uppercase dark:text-slate-400">
                        Описание
                      </p>
                      <p className="text-sm whitespace-pre-line text-gray-700 dark:text-slate-300">{draft.description}</p>
                    </div>
                  )}
                  <div className="mb-6 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 dark:border-amber-700/50 dark:bg-amber-900/20">
                    <p className="text-sm font-semibold text-amber-800 dark:text-amber-200">Внимание</p>
                    <p className="mt-1 text-sm text-amber-700 dark:text-amber-300/90">
                      При удалении направления все связанные занятия будут удалены из расписания без возможности
                      восстановления.
                    </p>
                  </div>
                  <div className="mt-2 flex gap-2 border-t border-gray-200 pt-4 dark:border-slate-700">
                    <button
                      type="button"
                      onClick={() => setIsEditing(true)}
                      className="flex-1 rounded-lg bg-amber-500 px-4 py-2 text-white hover:bg-amber-600 dark:bg-amber-700 dark:text-amber-50 dark:hover:bg-amber-800"
                    >
                      Редактировать
                    </button>
                    <button
                      type="button"
                      onClick={() => void handleDelete()}
                      disabled={isSubmitting}
                      className="flex-1 rounded-lg bg-red-500 px-4 py-2 text-white hover:bg-red-600 disabled:opacity-60 dark:bg-red-700 dark:text-red-50 dark:hover:bg-red-800"
                    >
                      Удалить
                    </button>
                  </div>
                </>
              ) : (
                <form
                  className="space-y-4"
                  onSubmit={(event) => {
                    event.preventDefault()
                    void handleSave()
                  }}
                >
                  <h3 className="pr-8 text-xl font-bold text-gray-900 dark:text-slate-100">
                    {draft.id === null ? 'Новое направление' : 'Редактирование'}
                  </h3>

                  <div>
                    <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-slate-300">Название направления</label>
                    <input
                      type="text"
                      value={draft.name}
                      onChange={(event) => setDraft((prev) => (prev ? { ...prev, name: event.target.value } : prev))}
                      className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-gray-900 focus:border-transparent focus:ring-2 focus:ring-amber-400 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-100"
                    />
                  </div>

                  <div>
                    <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-slate-300">Описание направления</label>
                    <textarea
                      rows={4}
                      value={draft.description ?? ''}
                      placeholder="Для кого это направление, что изучается на занятии и т.п."
                      onChange={(event) =>
                        setDraft((prev) => (prev ? { ...prev, description: event.target.value || null } : prev))
                      }
                      className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-gray-900 focus:border-transparent focus:ring-2 focus:ring-amber-400 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-100"
                    />
                  </div>

                  {error && <p className="text-sm text-red-600">{error}</p>}

                  <div className="flex gap-3 pt-2">
                    <button
                      type="submit"
                      disabled={isSubmitting}
                      className="flex-1 rounded-lg bg-amber-500 px-4 py-2 text-white hover:bg-amber-600 disabled:opacity-60 dark:bg-amber-700 dark:text-amber-50 dark:hover:bg-amber-800"
                    >
                      Сохранить
                    </button>
                    <button
                      type="button"
                      onClick={() => {
                        if (direction) {
                          setDraft(cloneDirection(direction))
                          setIsEditing(false)
                        } else {
                          onClose()
                        }
                        setError(null)
                      }}
                      className="flex-1 rounded-lg bg-gray-200 px-4 py-2 text-gray-700 hover:bg-gray-300 dark:bg-slate-700 dark:text-slate-200 dark:hover:bg-slate-600"
                    >
                      {draft.id === null ? 'Закрыть' : 'Отмена'}
                    </button>
                  </div>
                </form>
              )}
            </div>

            <button
              onClick={onClose}
              className="absolute top-2 right-2 cursor-pointer p-2 text-gray-400 transition-colors hover:text-gray-600 dark:text-slate-400 dark:hover:text-slate-200"
              aria-label="Закрыть"
              type="button"
            >
              <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
